# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # La session sera démarrée uniquement si nécessaire
    session: true

    # Router configuration pour supporter les attributs PHP 8
    router:
        utf8: true
        resource: '%kernel.project_dir%/src/Controller/'
        type: attribute

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
