<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260912010000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the missing admin audit log table on PostgreSQL';
    }

    public function up(Schema $schema): void
    {
        if (!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform) {
            return;
        }

        $this->addSql('CREATE TABLE IF NOT EXISTS admin_audit_log (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, actor_email VARCHAR(180) NOT NULL, event VARCHAR(100) NOT NULL, ip_address VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, target_user_id INTEGER DEFAULT NULL, PRIMARY KEY (id), CONSTRAINT FK_1F16C5C76C066AFE FOREIGN KEY (target_user_id) REFERENCES app_user (id) ON DELETE SET NULL)');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_1F16C5C76C066AFE ON admin_audit_log (target_user_id)');
    }

    public function down(Schema $schema): void
    {
        if (!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform) {
            return;
        }

        $this->addSql('DROP TABLE IF EXISTS admin_audit_log');
    }
}
